name = "seul-api"
main = "src/server.ts"
compatibility_date = "2026-08-29"
compatibility_flags = ["nodejs_compat"]

[env.production]
vars = { ENVIRONMENT = "production", ADMIN_EMAIL = "admin@seoulshop.cl", JWT_SECRET = "seul-king-os-jwt-production", DB_HOST = "ep-autumn-poetry-axvcuspa-pooler.c-4.us-east-2.aws.neon.tech", DB_USER = "neondb_owner", DB_PASSWORD = "npg_PltRoX3VBLg0", DB_NAME = "neondb" }
